[package]
edition = "2021"
name = "portfolio-server"
version = "0.1.0"

[profile.release]
lto = "thin"
strip = true

[dependencies]
mongodb = {version = "2.2.0"}
rocket = {version = "0.5.0-rc.2", features = ["json"]}
serde = "1.0.144"

bson = {version = "2", features = ["chrono-0_4"]}
chrono = "0.4"
dotenv = "0.15.0"
tokio = "1"
image = "0.24.3"
jsonwebtoken = "8.1.1"
