[package]
description = "API for my portfolio server"
edition = "2021"
name = "portfolio-server"
version = "0.1.0"

[profile.release]
codegen-units = 1
lto = "thin"
strip = true

[dependencies]
anyhow = "1.0.64"
chrono = "0.4"
dotenv = "0.15.0"
futures = "0.3"
tokio = "1.21"
image = {version = "0.24.3", default-features = false, features = ["jpeg", "jpeg_rayon", "png", "webp"]}
mongodb = "2.1.0"
okapi = {version = "0.6.0-alpha-1"}
rocket = {version = "0.5.0-rc.2", default-features = false, features = ["json"]}
rocket_okapi = {version = "0.8.0-rc.2", features = ["swagger", "secrets"]}
schemars = "0.8"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
